<?php
// app/Console/Commands/ExportAllahNames.php
//
// PURPOSE: Snapshot the 99 Names of Allah from the database
//          into a static local PHP file.
//
// WHY:     AllahNameSeeder reads from database/data/allah_names.php
//          instead of calling the Aladhan API on every fresh
//          deployment. This means:
//          - No internet dependency during production deploys
//          - No risk of the feature breaking if the API ever
//            goes down or changes its response format
//          - Consistent, predictable data every time
//
// WORKFLOW:
//   1. php artisan import:allah-names   (fetch fresh from API)
//   2. php artisan export:allah-names   (snapshot to local file)
//   3. Commit database/data/allah_names.php to git
//   4. db:seed --class=AllahNameSeeder now works completely
//      offline, anywhere, anytime.
//
// TO REFRESH DATA LATER: just repeat steps 1 and 2.

namespace App\Console\Commands;

use App\Models\AllahName;
use Illuminate\Console\Command;

class ExportAllahNames extends Command
{
    protected $signature   = 'export:allah-names';
    protected $description = 'Export Allah Names from database to a local static file for offline seeding';

    public function handle(): int
    {
        $names = AllahName::orderBy('position')->get();

        if ($names->isEmpty()) {
            $this->error('No Allah Names found in database.');
            $this->warn('Run "php artisan import:allah-names" first.');
            return self::FAILURE;
        }

        $lines = [
            '<?php',
            '',
            '// database/data/allah_names.php',
            '//',
            '// PURPOSE: Static snapshot of the 99 Names of Allah.',
            '// GENERATED BY: php artisan export:allah-names',
            '// GENERATED ON: ' . now()->toDateTimeString(),
            '//',
            '// WHY: AllahNameSeeder reads THIS file instead of calling',
            '//      the external API on every fresh deployment — avoids',
            '//      depending on a third-party API being online during',
            '//      production deploys.',
            '//',
            '// TO REFRESH: php artisan import:allah-names',
            '//             php artisan export:allah-names',
            '',
            'return [',
        ];

        foreach ($names as $name) {
            $lines[] = '    [';
            $lines[] = "        'position'        => {$name->position},";
            $lines[] = "        'name_ar'         => " . $this->quote($name->name_ar) . ',';
            $lines[] = "        'transliteration' => " . $this->quote($name->transliteration) . ',';
            $lines[] = "        'english_name'    => " . $this->quote($name->english_name) . ',';
            $lines[] = "        'meaning'         => " . $this->quote($name->meaning) . ',';
            $lines[] = "        'reference'       => " . $this->quote($name->reference) . ',';
            $lines[] = "        'slug'            => " . $this->quote($name->slug) . ',';
            $lines[] = "        'description'     => " . $this->quote($name->description) . ',';
            $lines[] = '    ],';
        }

        $lines[] = '];';
        $lines[] = '';

        $path = database_path('data/allah_names.php');

        // Ensure database/data/ directory exists
        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        file_put_contents($path, implode("\n", $lines));

        $this->info('');
        $this->info("✅ Exported {$names->count()} names to: database/data/allah_names.php");
        $this->info('   Commit this file to git so it ships with your app.');
        $this->info('   Going forward, db:seed will work fully offline.');

        return self::SUCCESS;
    }

    // ── Safely quote a value for the PHP array file ──────
    // null stays null, everything else is escaped properly
    // (handles Arabic UTF-8 text, quotes, backslashes safely)
    private function quote(?string $value): string
    {
        if ($value === null) {
            return 'null';
        }

        return var_export($value, true);
    }
}
