<?php
// database/seeders/ProphetSeeder.php

namespace Database\Seeders;

use App\Models\Prophet;
use Illuminate\Database\Seeder;

class ProphetSeeder extends Seeder
{
    public function run(): void
    {
        Prophet::truncate();

        // All 25 Prophets mentioned in the Quran
        // Format: [order, arabic, english, transliteration, title, period, quran_references]
        $prophets = [
            [
                'order'               => 1,
                'name_arabic'         => 'آدَم',
                'name_english'        => 'Adam',
                'name_transliteration' => 'Aadam',
                'slug'                => 'adam',
                'title'               => 'Father of Humanity',
                'title_arabic'           => 'أَبُو الْبَشَر',
                'title_transliteration'  => 'Abul Bashar',
                'period'              => 'Beginning of humanity',
                'mentioned_in_quran'  => 'Al-Baqarah 2:31-37, Al-A\'raf 7:19-25',
                'summary'             => 'Adam (AS) was the first human being and the first prophet. Allah created him from clay and breathed life into him, then taught him the names of all things. He and Hawwa (Eve) lived in Paradise until the trial with Iblis.',
            ],
            [
                'order'               => 2,
                'name_arabic'         => 'إِدرِيس',
                'name_english'        => 'Idris',
                'name_transliteration' => 'Idris',
                'slug'                => 'idris',
                'title'               => 'The Patient One',
                'title_arabic'           => 'النَّبِيُّ الصَّابِر',
                'title_transliteration'  => 'An-Nabiyus Sabir',
                'period'              => 'Antediluvian period',
                'mentioned_in_quran'  => 'Maryam 19:56-57, Al-Anbiya 21:85-86',
                'summary'             => 'Idris (AS) was known for his great patience and was raised to a high station by Allah. Many scholars identify him with Enoch of the Biblical tradition.',
            ],
            [
                'order'               => 3,
                'name_arabic'         => 'نُوح',
                'name_english'        => 'Noah',
                'name_transliteration' => 'Nuh',
                'slug'                => 'nuh',
                'title'               => 'Grateful Servant of Allah',
                'title_arabic'           => 'شَاكِرُ اللَّه',
                'title_transliteration'  => 'Shakirullah',
                'period'              => 'circa 3000 BCE',
                'mentioned_in_quran'  => 'Nuh 71:1-28, Hud 11:25-49',
                'summary'             => 'Nuh (AS) preached for 950 years and built the Ark by Allah\'s command. When his people refused to believe, Allah sent the great flood. He is considered one of the five greatest prophets (Ulul \'Azm).',
            ],
            [
                'order'               => 4,
                'name_arabic'         => 'هُود',
                'name_english'        => 'Hud',
                'name_transliteration' => 'Hud',
                'slug'                => 'hud',
                'title'               => 'Prophet to the People of \'Ad',
                'title_arabic'           => 'نَبِيُّ عَاد',
                'title_transliteration'  => 'Nabiyyu Aad',
                'period'              => 'Ancient Arabia',
                'mentioned_in_quran'  => 'Hud 11:50-60, Al-A\'raf 7:65-72',
                'summary'             => 'Hud (AS) was sent to the proud and powerful people of \'Ad in ancient Arabia. They rejected him and were destroyed by a furious wind for seven nights and eight days.',
            ],
            [
                'order'               => 5,
                'name_arabic'         => 'صَالِح',
                'name_english'        => 'Salih',
                'name_transliteration' => 'Salih',
                'slug'                => 'salih',
                'title'               => 'Prophet to the People of Thamud',
                'title_arabic'           => 'نَبِيُّ ثَمُود',
                'title_transliteration'  => 'Nabiyyu Thamud',
                'period'              => 'Ancient Arabia',
                'mentioned_in_quran'  => 'Hud 11:61-68, Al-A\'raf 7:73-79',
                'summary'             => 'Salih (AS) was sent to the Thamud people. Allah gave them a she-camel as a miracle and sign. When they slaughtered her in defiance, punishment came upon them.',
            ],
            [
                'order'               => 6,
                'name_arabic'         => 'إِبرَاهِيم',
                'name_english'        => 'Abraham',
                'name_transliteration' => 'Ibrahim',
                'slug'                => 'ibrahim',
                'title'               => 'Khalilullah — Friend of Allah',
                'title_arabic'           => 'خَلِيلُ اللَّه',
                'title_transliteration'  => 'Khalilullah',
                'period'              => 'circa 1800 BCE',
                'mentioned_in_quran'  => 'Al-Baqarah 2:124-132, Ibrahim 14:35-41',
                'summary'             => 'Ibrahim (AS) is one of the greatest prophets and is called "Khalilullah" (Friend of Allah). He smashed the idols of his people, was thrown into fire by Nimrod but emerged unharmed, built the Ka\'bah with his son Ismail, and was tested with the command to sacrifice his son.',
            ],
            [
                'order'               => 7,
                'name_arabic'         => 'لُوط',
                'name_english'        => 'Lot',
                'name_transliteration' => 'Lut',
                'slug'                => 'lut',
                'title'               => 'Prophet to the People of Sodom',
                'title_arabic'           => 'نَبِيُّ اللَّه',
                'title_transliteration'  => 'Nabiyyullah',
                'period'              => 'circa 1800 BCE',
                'mentioned_in_quran'  => 'Hud 11:77-83, Al-A\'raf 7:80-84',
                'summary'             => 'Lut (AS) was the nephew of Ibrahim (AS) and was sent to the people of Sodom who had fallen into grave sins. When they rejected his message, Allah destroyed their city.',
            ],
            [
                'order'               => 8,
                'name_arabic'         => 'إِسمَاعِيل',
                'name_english'        => 'Ishmael',
                'name_transliteration' => 'Ismail',
                'slug'                => 'ismail',
                'title'               => 'Dhabihullah — The one offered in sacrifice',
                'title_arabic'           => 'ذَبِيحُ اللَّه',
                'title_transliteration'  => 'Dhabihullah',
                'period'              => 'circa 1750 BCE',
                'mentioned_in_quran'  => 'As-Saffat 37:100-111, Al-Baqarah 2:127',
                'summary'             => 'Ismail (AS) was the firstborn son of Ibrahim (AS). As an infant, he and his mother Hajar were left in the barren valley of Makkah. He helped his father build the Ka\'bah and was willing to be sacrificed when Allah tested Ibrahim.',
            ],
            [
                'order'               => 9,
                'name_arabic'         => 'إِسحَاق',
                'name_english'        => 'Isaac',
                'name_transliteration' => 'Ishaq',
                'slug'                => 'ishaq',
                'title'               => 'Son of Ibrahim',
                'title_arabic'           => 'نَبِيُّ اللَّه',
                'title_transliteration'  => 'Nabiyyullah',
                'period'              => 'circa 1750 BCE',
                'mentioned_in_quran'  => 'Hud 11:71, Al-Anbiya 21:72',
                'summary'             => 'Ishaq (AS) was the second son of Ibrahim (AS) born to Sarah in her old age as a miraculous gift from Allah. He continued the prophetic lineage.',
            ],
            [
                'order'               => 10,
                'name_arabic'         => 'يَعقُوب',
                'name_english'        => 'Jacob',
                'name_transliteration' => 'Yaqub',
                'slug'                => 'yaqub',
                'title'               => 'Israel — Servant of Allah',
                'title_arabic'           => 'إِسرَائِيل',
                'title_transliteration'  => 'Isra\'il',
                'period'              => 'circa 1700 BCE',
                'mentioned_in_quran'  => 'Al-Baqarah 2:132, Yusuf 12:4-6',
                'summary'             => 'Yaqub (AS) was the son of Ishaq (AS). He was also known as Israel. His 12 sons became the 12 tribes of Israel. His story is deeply intertwined with that of his beloved son Yusuf.',
            ],
            [
                'order'               => 11,
                'name_arabic'         => 'يُوسُف',
                'name_english'        => 'Joseph',
                'name_transliteration' => 'Yusuf',
                'slug'                => 'yusuf',
                'title'               => 'The Most Beautiful Story',
                'title_arabic'           => 'الصِّدِّيق',
                'title_transliteration'  => 'As-Siddiq',
                'period'              => 'circa 1650 BCE',
                'mentioned_in_quran'  => 'Yusuf 12:1-111 (entire surah)',
                'summary'             => 'Yusuf (AS) had the entire Surah Yusuf dedicated to his story — called "the best of stories" by Allah. He was thrown into a well by his jealous brothers, sold into slavery in Egypt, imprisoned falsely, and ultimately rose to become the treasurer of Egypt. His patience and trust in Allah is a timeless lesson.',
            ],
            [
                'order'               => 12,
                'name_arabic'         => 'أَيُّوب',
                'name_english'        => 'Job',
                'name_transliteration' => 'Ayyub',
                'slug'                => 'ayyub',
                'title'               => 'Symbol of Patience',
                'title_arabic'           => 'الصَّابِر',
                'title_transliteration'  => 'As-Sabir',
                'period'              => 'Ancient times',
                'mentioned_in_quran'  => 'Al-Anbiya 21:83-84, Sad 38:41-44',
                'summary'             => 'Ayyub (AS) was tested with severe illness, loss of wealth and family for years. He never complained against Allah. When he called upon Allah in humility, he was completely restored. His name is synonymous with sabr (patience).',
            ],
            [
                'order'               => 13,
                'name_arabic'         => 'شُعَيب',
                'name_english'        => 'Jethro',
                'name_transliteration' => 'Shu\'ayb',
                'slug'                => 'shuayb',
                'title'               => 'Prophet to Midian',
                'title_arabic'           => 'خَطِيبُ الْأَنْبِيَاء',
                'title_transliteration'  => 'Khateebul Anbiya',
                'period'              => 'circa 1500 BCE',
                'mentioned_in_quran'  => 'Hud 11:84-95, Al-A\'raf 7:85-93',
                'summary'             => 'Shu\'ayb (AS) was sent to the people of Midian who were cheating in trade and business. He called them to honesty and fair dealing. They rejected him and were destroyed by a mighty blast.',
            ],
            [
                'order'               => 14,
                'name_arabic'         => 'مُوسَى',
                'name_english'        => 'Moses',
                'name_transliteration' => 'Musa',
                'slug'                => 'musa',
                'title'               => 'Kalimullah — One who spoke to Allah',
                'title_arabic'           => 'كَلِيمُ اللَّه',
                'title_transliteration'  => 'Kalimullah',
                'period'              => 'circa 1300 BCE',
                'mentioned_in_quran'  => 'Al-Baqarah 2:49-61, Ta-Ha 20:9-98',
                'summary'             => 'Musa (AS) is the most mentioned prophet in the Quran. Born in Egypt under Pharaoh\'s oppression, raised in Pharaoh\'s palace, he fled to Midian, received prophethood at the burning bush, returned to free the Israelites, parted the Red Sea, and received the Torah on Mount Sinai.',
            ],
            [
                'order'               => 15,
                'name_arabic'         => 'هَارُون',
                'name_english'        => 'Aaron',
                'name_transliteration' => 'Harun',
                'slug'                => 'harun',
                'title'               => 'Brother and Helper of Musa',
                'title_arabic'           => 'نَبِيُّ اللَّه',
                'title_transliteration'  => 'Nabiyyullah',
                'period'              => 'circa 1300 BCE',
                'mentioned_in_quran'  => 'Ta-Ha 20:29-36, Al-A\'raf 7:142',
                'summary'             => 'Harun (AS) was the elder brother of Musa (AS) and was granted prophethood to assist him. He was known for his eloquence and was left in charge of the Israelites while Musa went to receive the Torah.',
            ],
            [
                'order'               => 16,
                'name_arabic'         => 'ذُو الكِفل',
                'name_english'        => 'Ezekiel',
                'name_transliteration' => 'Dhul-Kifl',
                'slug'                => 'dhul-kifl',
                'title'               => 'The Patient and Righteous',
                'title_arabic'           => 'الصَّابِر الصَّالِح',
                'title_transliteration'  => 'As-Sabirus Salih',
                'period'              => 'Ancient times',
                'mentioned_in_quran'  => 'Al-Anbiya 21:85-86, Sad 38:48',
                'summary'             => 'Dhul-Kifl (AS) is mentioned among the patient and righteous. His exact story is not detailed in the Quran, but he is praised for his patience and righteousness.',
            ],
            [
                'order'               => 17,
                'name_arabic'         => 'دَاوُود',
                'name_english'        => 'David',
                'name_transliteration' => 'Dawud',
                'slug'                => 'dawud',
                'title'               => 'King and Prophet',
                'title_arabic'           => 'خَلِيفَةُ اللَّه',
                'title_transliteration'  => 'Khalifatullah',
                'period'              => 'circa 1000 BCE',
                'mentioned_in_quran'  => 'Al-Baqarah 2:251, Sad 38:17-26',
                'summary'             => 'Dawud (AS) was both a prophet and a great king. As a young man he defeated the giant Jalut (Goliath). Allah gave him the Zabur (Psalms) and made iron soft in his hands. He had a beautiful voice that caused birds and mountains to praise Allah with him.',
            ],
            [
                'order'               => 18,
                'name_arabic'         => 'سُلَيمَان',
                'name_english'        => 'Solomon',
                'name_transliteration' => 'Sulayman',
                'slug'                => 'sulayman',
                'title'               => 'The Wise King',
                'title_arabic'           => 'نَبِيٌّ مَلِك',
                'title_transliteration'  => 'Nabiyyun Malik',
                'period'              => 'circa 970 BCE',
                'mentioned_in_quran'  => 'An-Naml 27:15-44, Sad 38:30-40',
                'summary'             => 'Sulayman (AS) was given extraordinary gifts — he could speak to animals and birds, command the jinn, and the wind was made subservient to him. He built the great temple in Jerusalem. His encounter with the Queen of Sheba (Bilqis) is one of the most famous Quranic narratives.',
            ],
            [
                'order'               => 19,
                'name_arabic'         => 'إِلِيَاس',
                'name_english'        => 'Elias',
                'name_transliteration' => 'Ilyas',
                'slug'                => 'ilyas',
                'title'               => 'Prophet to the People of Baal',
                'title_arabic'           => 'نَبِيُّ اللَّه',
                'title_transliteration'  => 'Nabiyyullah',
                'period'              => 'circa 850 BCE',
                'mentioned_in_quran'  => 'As-Saffat 37:123-132, Al-An\'am 6:85',
                'summary'             => 'Ilyas (AS) was sent to a people who had turned to idol worship, specifically the idol Ba\'l. He called them back to monotheism with great courage.',
            ],
            [
                'order'               => 20,
                'name_arabic'         => 'اليَسَع',
                'name_english'        => 'Elisha',
                'name_transliteration' => 'Al-Yasa\'',
                'slug'                => 'al-yasa',
                'title'               => 'Among the Best of People',
                'title_arabic'           => 'مِنَ الْأَخْيَار',
                'title_transliteration'  => 'Minal Akhyar',
                'period'              => 'circa 850 BCE',
                'mentioned_in_quran'  => 'Al-An\'am 6:86, Sad 38:48',
                'summary'             => 'Al-Yasa\' (AS) is mentioned among the prophets who were guided by Allah and chosen above the nations. He was the successor of Ilyas (AS).',
            ],
            [
                'order'               => 21,
                'name_arabic'         => 'يُونُس',
                'name_english'        => 'Jonah',
                'name_transliteration' => 'Yunus',
                'slug'                => 'yunus',
                'title'               => 'Dhun-Nun — Man of the Whale',
                'title_arabic'           => 'ذُو النُّون',
                'title_transliteration'  => 'Dhun-Nun',
                'period'              => 'circa 800 BCE',
                'mentioned_in_quran'  => 'Yunus 10:98, As-Saffat 37:139-148',
                'summary'             => 'Yunus (AS) left his people without Allah\'s permission and was swallowed by a giant whale. In the belly of the whale he made the famous dua: "There is no god but You, Glory be to You, I was indeed of the wrongdoers." Allah forgave him and he was released.',
            ],
            [
                'order'               => 22,
                'name_arabic'         => 'زَكَرِيَّا',
                'name_english'        => 'Zechariah',
                'name_transliteration' => 'Zakariyya',
                'slug'                => 'zakariyya',
                'title'               => 'Guardian of Maryam',
                'title_arabic'           => 'نَبِيُّ اللَّه',
                'title_transliteration'  => 'Nabiyyullah',
                'period'              => 'circa 1st century BCE',
                'mentioned_in_quran'  => 'Maryam 19:2-11, Ali \'Imran 3:37-41',
                'summary'             => 'Zakariyya (AS) was the guardian of Maryam (Mary). In his old age, seeing the miraculous provision Maryam received from Allah, he prayed for a child. Allah gave him Yahya (John the Baptist) as a miracle.',
            ],
            [
                'order'               => 23,
                'name_arabic'         => 'يَحيَى',
                'name_english'        => 'John',
                'name_transliteration' => 'Yahya',
                'slug'                => 'yahya',
                'title'               => 'Granted wisdom in youth',
                'title_arabic'           => 'سَيِّدًا وَحَصُورًا',
                'title_transliteration'  => 'Sayyidan wa Hasura',
                'period'              => 'circa 1st century BCE',
                'mentioned_in_quran'  => 'Maryam 19:12-15, Ali \'Imran 3:39',
                'summary'             => 'Yahya (AS) was given wisdom by Allah while still a child. He confirmed the word of Allah regarding Isa (AS). He was known for his piety and asceticism.',
            ],
            [
                'order'               => 24,
                'name_arabic'         => 'عِيسَى',
                'name_english'        => 'Jesus',
                'name_transliteration' => 'Isa',
                'slug'                => 'isa',
                'title'               => 'Ruhullah — Spirit of Allah',
                'title_arabic'           => 'رُوحُ اللَّه',
                'title_transliteration'  => 'Ruhullah',
                'period'              => 'circa 4 BCE – 30 CE',
                'mentioned_in_quran'  => 'Ali \'Imran 3:45-55, Maryam 19:16-34',
                'summary'             => 'Isa (AS) was born miraculously to the virgin Maryam. He spoke from the cradle, healed the sick, raised the dead, and was given the Injeel (Gospel). He is one of the five greatest prophets. Muslims believe he was not crucified but raised to the heavens by Allah and will return before the Day of Judgement.',
            ],
            [
                'order'               => 25,
                'name_arabic'         => 'مُحَمَّد ﷺ',
                'name_english'        => 'Muhammad ﷺ',
                'name_transliteration' => 'Muhammad ',
                'slug'                => 'muhammad',
                'title'               => 'Messenger of Allah ﷺ — Seal of the Prophets • Mercy to All Worlds',
                'title_arabic'           => 'حَبِيبُ اللَّه',
                'title_transliteration'  => 'Habibullah',
                'period'              => '570 CE – 632 CE',
                'mentioned_in_quran'  => 'Surah Aal-Imran 3:144, Surah Al-Ahzab 33:40, Surah Muhammad 47:2, Surah Al-Fath 48:29, among many others',
                'summary'             => 'Muhammad ﷺ is the final and greatest prophet, sent as a mercy to all of mankind. Born in Makkah, he received the first revelation at age 40 in the Cave of Hira. Over 23 years, the Quran was revealed to him. He faced persecution in Makkah, made Hijra to Madinah, and united the Arab tribes under Islam before returning to Makkah in triumph. He is the best of all creation.',
            ],
        ];

        foreach ($prophets as $prophet) {
            Prophet::create($prophet);
        }

        $this->command->info('✅ Prophets seeded: All 25 Prophets of Islam');
    }
}
