<?php
// database/seeders/SurahSeeder.php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        Surah::truncate();

        // Complete list of all 114 Surahs
        // Format: [number, arabic_name, transliteration, english_name, revelation_type, ayah_count, page]
        $surahs = [
            [1,   'الفَاتِحَة',      'Al-Fatihah',       'The Opening',            'meccan',  7,   1],
            [2,   'البَقَرَة',       'Al-Baqarah',        'The Cow',                'medinan', 286, 2],
            [3,   'آل عِمرَان',     'Ali \'Imran',        'Family of Imran',        'medinan', 200, 50],
            [4,   'النِّسَاء',       'An-Nisa',           'The Women',              'medinan', 176, 77],
            [5,   'المَائِدَة',      'Al-Ma\'idah',       'The Table Spread',       'medinan', 120, 106],
            [6,   'الأَنعَام',       'Al-An\'am',         'The Cattle',             'meccan',  165, 128],
            [7,   'الأَعرَاف',       'Al-A\'raf',         'The Heights',            'meccan',  206, 151],
            [8,   'الأَنفَال',       'Al-Anfal',          'The Spoils of War',      'medinan', 75,  177],
            [9,   'التَّوبَة',       'At-Tawbah',         'The Repentance',         'medinan', 129, 187],
            [10,  'يُونس',           'Yunus',             'Jonah',                  'meccan',  109, 208],
            [11,  'هُود',            'Hud',               'Hud',                    'meccan',  123, 221],
            [12,  'يُوسُف',          'Yusuf',             'Joseph',                 'meccan',  111, 235],
            [13,  'الرَّعد',         'Ar-Ra\'d',          'The Thunder',            'medinan', 43,  249],
            [14,  'إِبرَاهِيم',      'Ibrahim',           'Abraham',                'meccan',  52,  255],
            [15,  'الحِجر',          'Al-Hijr',           'The Rocky Tract',        'meccan',  99,  262],
            [16,  'النَّحل',         'An-Nahl',           'The Bee',                'meccan',  128, 267],
            [17,  'الإِسرَاء',       'Al-Isra',           'The Night Journey',      'meccan',  111, 282],
            [18,  'الكَهف',          'Al-Kahf',           'The Cave',               'meccan',  110, 293],
            [19,  'مَريَم',          'Maryam',            'Mary',                   'meccan',  98,  305],
            [20,  'طه',              'Ta-Ha',             'Ta-Ha',                  'meccan',  135, 312],
            [21,  'الأَنبِيَاء',     'Al-Anbiya',         'The Prophets',           'meccan',  112, 322],
            [22,  'الحَج',           'Al-Hajj',           'The Pilgrimage',         'medinan', 78,  332],
            [23,  'المُؤمِنُون',     'Al-Mu\'minun',      'The Believers',          'meccan',  118, 342],
            [24,  'النُّور',         'An-Nur',            'The Light',              'medinan', 64,  350],
            [25,  'الفُرقَان',       'Al-Furqan',         'The Criterion',          'meccan',  77,  359],
            [26,  'الشُّعَرَاء',     'Ash-Shu\'ara',      'The Poets',              'meccan',  227, 367],
            [27,  'النَّمل',         'An-Naml',           'The Ant',                'meccan',  93,  377],
            [28,  'القَصَص',         'Al-Qasas',          'The Stories',            'meccan',  88,  385],
            [29,  'العَنكَبُوت',     'Al-\'Ankabut',      'The Spider',             'meccan',  69,  396],
            [30,  'الرُّوم',         'Ar-Rum',            'The Romans',             'meccan',  60,  404],
            [31,  'لُقمَان',         'Luqman',            'Luqman',                 'meccan',  34,  411],
            [32,  'السَّجدَة',       'As-Sajdah',         'The Prostration',        'meccan',  30,  415],
            [33,  'الأَحزَاب',       'Al-Ahzab',          'The Combined Forces',    'medinan', 73,  418],
            [34,  'سَبَأ',           'Saba',              'Sheba',                  'meccan',  54,  428],
            [35,  'فَاطِر',          'Fatir',             'Originator',             'meccan',  45,  434],
            [36,  'يس',              'Ya-Sin',            'Ya Sin',                 'meccan',  83,  440],
            [37,  'الصَّافَّات',     'As-Saffat',         'Those Who Set the Ranks', 'meccan',  182, 446],
            [38,  'ص',               'Sad',               'The Letter "Sad"',       'meccan',  88,  453],
            [39,  'الزُّمَر',        'Az-Zumar',          'The Troops',             'meccan',  75,  458],
            [40,  'غَافِر',          'Ghafir',            'The Forgiver',           'meccan',  85,  467],
            [41,  'فُصِّلَت',        'Fussilat',          'Explained in Detail',    'meccan',  54,  477],
            [42,  'الشُّورى',        'Ash-Shuraa',        'The Consultation',       'meccan',  53,  483],
            [43,  'الزُّخرُف',       'Az-Zukhruf',        'The Ornaments of Gold',  'meccan',  89,  489],
            [44,  'الدُّخَان',       'Ad-Dukhan',         'The Smoke',              'meccan',  59,  496],
            [45,  'الجَاثِيَة',      'Al-Jathiyah',       'The Crouching',          'meccan',  37,  499],
            [46,  'الأَحقَاف',       'Al-Ahqaf',          'The Wind-Curved Sandhills', 'meccan', 35,  502],
            [47,  'مُحَمَّد',        'Muhammad',          'Muhammad',               'medinan', 38,  507],
            [48,  'الفَتح',          'Al-Fath',           'The Victory',            'medinan', 29,  511],
            [49,  'الحُجُرَات',      'Al-Hujurat',        'The Rooms',              'medinan', 18,  515],
            [50,  'ق',               'Qaf',               'The Letter "Qaf"',       'meccan',  45,  518],
            [51,  'الذَّارِيَات',    'Adh-Dhariyat',      'The Winnowing Winds',    'meccan',  60,  520],
            [52,  'الطُّور',         'At-Tur',            'The Mount',              'meccan',  49,  523],
            [53,  'النَّجم',         'An-Najm',           'The Star',               'meccan',  62,  526],
            [54,  'القَمَر',         'Al-Qamar',          'The Moon',               'meccan',  55,  528],
            [55,  'الرَّحمَن',       'Ar-Rahman',         'The Beneficent',         'medinan', 78,  531],
            [56,  'الوَاقِعَة',      'Al-Waqi\'ah',       'The Inevitable',         'meccan',  96,  534],
            [57,  'الحَدِيد',        'Al-Hadid',          'The Iron',               'medinan', 29,  537],
            [58,  'المُجَادِلَة',    'Al-Mujadila',       'The Pleading Woman',     'medinan', 22,  542],
            [59,  'الحَشر',          'Al-Hashr',          'The Exile',              'medinan', 24,  545],
            [60,  'المُمتَحَنَة',    'Al-Mumtahanah',     'She That is to be Examined', 'medinan', 13, 549],
            [61,  'الصَّف',          'As-Saf',            'The Ranks',              'medinan', 14,  551],
            [62,  'الجُمُعَة',       'Al-Jumu\'ah',       'Friday',                 'medinan', 11,  553],
            [63,  'المُنَافِقُون',   'Al-Munafiqun',      'The Hypocrites',         'medinan', 11,  554],
            [64,  'التَّغَابُن',     'At-Taghabun',       'The Mutual Disillusion', 'medinan', 18,  556],
            [65,  'الطَّلاق',        'At-Talaq',          'The Divorce',            'medinan', 12,  558],
            [66,  'التَّحرِيم',      'At-Tahrim',         'The Prohibition',        'medinan', 12,  560],
            [67,  'المُلك',          'Al-Mulk',           'The Sovereignty',        'meccan',  30,  562],
            [68,  'القَلَم',         'Al-Qalam',          'The Pen',                'meccan',  52,  564],
            [69,  'الحَاقَّة',       'Al-Haqqah',         'The Reality',            'meccan',  52,  566],
            [70,  'المَعَارِج',      'Al-Ma\'arij',       'The Ascending Stairways', 'meccan',  44,  568],
            [71,  'نُوح',            'Nuh',               'Noah',                   'meccan',  28,  570],
            [72,  'الجِن',           'Al-Jinn',           'The Jinn',               'meccan',  28,  572],
            [73,  'المُزَّمِّل',     'Al-Muzzammil',      'The Enshrouded One',     'meccan',  20,  574],
            [74,  'المُدَّثِّر',     'Al-Muddaththir',    'The Cloaked One',        'meccan',  56,  575],
            [75,  'القِيَامَة',      'Al-Qiyamah',        'The Resurrection',       'meccan',  40,  577],
            [76,  'الإِنسَان',       'Al-Insan',          'The Man',                'medinan', 31,  578],
            [77,  'المُرسَلاَت',     'Al-Mursalat',       'The Emissaries',         'meccan',  50,  580],
            [78,  'النَّبَأ',        'An-Naba',           'The Tidings',            'meccan',  40,  582],
            [79,  'النَّازِعَات',    'An-Nazi\'at',       'Those Who Drag Forth',   'meccan',  46,  583],
            [80,  'عَبَسَ',          '\'Abasa',           'He Frowned',             'meccan',  42,  585],
            [81,  'التَّكوِير',      'At-Takwir',         'The Overthrowing',       'meccan',  29,  586],
            [82,  'الانفِطَار',      'Al-Infitar',        'The Cleaving',           'meccan',  19,  587],
            [83,  'المُطَفِّفِين',   'Al-Mutaffifin',     'The Defrauding',         'meccan',  36,  587],
            [84,  'الانشِقَاق',      'Al-Inshiqaq',       'The Sundering',          'meccan',  25,  589],
            [85,  'البُرُوج',        'Al-Buruj',          'The Mansions of Stars',  'meccan',  22,  590],
            [86,  'الطَّارِق',       'At-Tariq',          'The Nightcommer',        'meccan',  17,  591],
            [87,  'الأَعلَى',        'Al-A\'la',          'The Most High',          'meccan',  19,  591],
            [88,  'الغَاشِيَة',      'Al-Ghashiyah',      'The Overwhelming',       'meccan',  26,  592],
            [89,  'الفَجر',          'Al-Fajr',           'The Dawn',               'meccan',  30,  593],
            [90,  'البَلَد',         'Al-Balad',          'The City',               'meccan',  20,  594],
            [91,  'الشَّمس',         'Ash-Shams',         'The Sun',                'meccan',  15,  595],
            [92,  'اللَّيل',         'Al-Layl',           'The Night',              'meccan',  21,  595],
            [93,  'الضُّحى',         'Ad-Duhaa',          'The Morning Hours',      'meccan',  11,  596],
            [94,  'الشَّرح',         'Ash-Sharh',         'The Relief',             'meccan',  8,   596],
            [95,  'التِّين',         'At-Tin',            'The Fig',                'meccan',  8,   597],
            [96,  'العَلَق',         'Al-\'Alaq',         'The Clot',               'meccan',  19,  597],
            [97,  'القَدر',          'Al-Qadr',           'The Power',              'meccan',  5,   598],
            [98,  'البَيِّنَة',      'Al-Bayyinah',       'The Clear Proof',        'medinan', 8,   598],
            [99,  'الزَّلزَلَة',     'Az-Zalzalah',       'The Earthquake',         'medinan', 8,   599],
            [100, 'العَادِيَات',     'Al-\'Adiyat',       'The Courser',            'meccan',  11,  599],
            [101, 'القَارِعَة',      'Al-Qari\'ah',       'The Calamity',           'meccan',  11,  600],
            [102, 'التَّكَاثُر',     'At-Takathur',       'The Rivalry in World Increase', 'meccan', 8, 600],
            [103, 'العَصر',          'Al-\'Asr',          'The Declining Day',      'meccan',  3,   601],
            [104, 'الهُمَزَة',       'Al-Humazah',        'The Traducer',           'meccan',  9,   601],
            [105, 'الفِيل',          'Al-Fil',            'The Elephant',           'meccan',  5,   601],
            [106, 'قُرَيش',          'Quraysh',           'Quraysh',                'meccan',  4,   602],
            [107, 'المَاعُون',       'Al-Ma\'un',         'The Small Kindnesses',   'meccan',  7,   602],
            [108, 'الكَوثَر',        'Al-Kawthar',        'The Abundance',          'meccan',  3,   602],
            [109, 'الكَافِرُون',     'Al-Kafirun',        'The Disbelievers',       'meccan',  6,   603],
            [110, 'النَّصر',         'An-Nasr',           'The Divine Support',     'medinan', 3,   603],
            [111, 'المَسَد',         'Al-Masad',          'The Palm Fiber',         'meccan',  5,   603],
            [112, 'الإِخلاَص',       'Al-Ikhlas',         'The Sincerity',          'meccan',  4,   604],
            [113, 'الفَلَق',         'Al-Falaq',          'The Daybreak',           'meccan',  5,   604],
            [114, 'النَّاس',         'An-Nas',            'The Mankind',            'meccan',  6,   604],
        ];

        foreach ($surahs as $surah) {
            Surah::create([
                'number'               => $surah[0],
                'name_arabic'          => $surah[1],
                'name_transliteration' => $surah[2],
                'name_english'         => $surah[3],
                'revelation_type'      => $surah[4],
                'ayah_count'           => $surah[5],
                'page_number'          => $surah[6],
            ]);
        }

        $this->command->info('✅ Surahs seeded: All 114 Surahs of the Holy Quran');
    }
}
